apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: redis

spec:
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {} 

  replicas: 1
  selector:
    matchLabels:
      app: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis

spec:
  type: ClusterIP
  ports:
  - name: redis-service-port
    port: 6379
    targetPort: 6379
  selector:
    app: redis